M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date Tue 21 Mar 2023 11:42:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-21T11:42:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X3.9374Y-1.6142
T0
M30
